# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Mar 17 22:24:43 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(667, 446)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(399, 324))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelList = QtGui.QListView(self.centralwidget)
        self.labelList.setObjectName("labelList")
        self.gridLayout.addWidget(self.labelList, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.markReadItems = QtGui.QCheckBox(self.centralwidget)
        self.markReadItems.setChecked(True)
        self.markReadItems.setObjectName("markReadItems")
        self.verticalLayout.addWidget(self.markReadItems)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deliveryTimeLabel = QtGui.QLabel(self.centralwidget)
        self.deliveryTimeLabel.setObjectName("deliveryTimeLabel")
        self.horizontalLayout.addWidget(self.deliveryTimeLabel)
        self.deliveryTime = QtGui.QTimeEdit(self.centralwidget)
        self.deliveryTime.setTime(QtCore.QTime(6, 0, 0))
        self.deliveryTime.setObjectName("deliveryTime")
        self.horizontalLayout.addWidget(self.deliveryTime)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sendToPrinter = QtGui.QCheckBox(self.centralwidget)
        self.sendToPrinter.setChecked(True)
        self.sendToPrinter.setObjectName("sendToPrinter")
        self.horizontalLayout_2.addWidget(self.sendToPrinter)
        self.printerList = QtGui.QComboBox(self.centralwidget)
        self.printerList.setObjectName("printerList")
        self.horizontalLayout_2.addWidget(self.printerList)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.maxArticles = QtGui.QSpinBox(self.centralwidget)
        self.maxArticles.setMinimum(1)
        self.maxArticles.setMaximum(999)
        self.maxArticles.setProperty("value", QtCore.QVariant(20))
        self.maxArticles.setObjectName("maxArticles")
        self.horizontalLayout_3.addWidget(self.maxArticles)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(308, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtGui.QSpacerItem(428, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.printButton = QtGui.QPushButton(self.centralwidget)
        self.printButton.setObjectName("printButton")
        self.horizontalLayout_5.addWidget(self.printButton)
        self.previewButton = QtGui.QPushButton(self.centralwidget)
        self.previewButton.setObjectName("previewButton")
        self.horizontalLayout_5.addWidget(self.previewButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Google Reader Newspaper", None, QtGui.QApplication.UnicodeUTF8))
        self.markReadItems.setText(QtGui.QApplication.translate("MainWindow", "Mark printed items as read in my Google Reader", None, QtGui.QApplication.UnicodeUTF8))
        self.deliveryTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "Print my newspaper at", None, QtGui.QApplication.UnicodeUTF8))
        self.sendToPrinter.setText(QtGui.QApplication.translate("MainWindow", "Automatically send to printer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Maximum articles per blog to print", None, QtGui.QApplication.UnicodeUTF8))
        self.printButton.setText(QtGui.QApplication.translate("MainWindow", "Print now", None, QtGui.QApplication.UnicodeUTF8))
        self.previewButton.setText(QtGui.QApplication.translate("MainWindow", "Preview...", None, QtGui.QApplication.UnicodeUTF8))

